/** @format */

export const pageNames = {
  page01: {
    title: "Inaugurazione",
    sectionNumber: "01",
    image: "./src/assets/mulino.jpg",
    alt: "",
    ITdescription: "Strumento ideato ed utilizzato per la raccolta del fior di sale. Il retino sottile che forma la pala consente di trattenere il sottile velo di sale superficiale (fior di sale) formatosi sulla superficie delle vasche salanti separandolo dalla salamoia sottostante. Tutto il processo è rigorosamente manuale.",
    ENdescription: "This tool is used for harvesting the 'Fior di Sale'. The sieving-shovel allows to keep the thin layer of salt cristals (fior di sale) grown on the crystallizer pan surface separating it from the underlying brine. The whole process is strictly executed by hand.",
  },
  page02: {
    title: "Restauro",
    sectionNumber: "02",
    image: "./src/assets/mulino.jpg",
    alt: "",
    ITdescription: "Strumento ideato ed utilizzato per la raccolta del fior di sale. Il retino sottile che forma la pala consente di trattenere il sottile velo di sale superficiale (fior di sale) formatosi sulla superficie delle vasche salanti separandolo dalla salamoia sottostante. Tutto il processo è rigorosamente manuale.",
    ENdescription: "This tool is used for harvesting the 'Fior di Sale'. The sieving-shovel allows to keep the thin layer of salt cristals (fior di sale) grown on the crystallizer pan surface separating it from the underlying brine. The whole process is strictly executed by hand.",
  },
  page03: {
    title: "Setaccio",
    sectionNumber: "03",
    image: "./src/assets/Setaccio.jpg",
    alt: "",
    ITdescription: "Strumento ideato ed utilizzato per la raccolta del fior di sale. Il retino sottile che forma la pala consente di trattenere il sottile velo di sale superficiale (fior di sale) formatosi sulla superficie delle vasche salanti separandolo dalla salamoia sottostante. Tutto il processo è rigorosamente manuale.",
    ENdescription: "This tool is used for harvesting the 'Fior di Sale'. The sieving-shovel allows to keep the thin layer of salt cristals (fior di sale) grown on the crystallizer pan surface separating it from the underlying brine. The whole process is strictly executed by hand.",
  },
  page04: {
    title: "Spira di archimede",
    sectionNumber: "04",
    image: "./src/assets/SpiraDiArchimede.png",
    alt: "",
    ITdescription: "Strumento ideato ed utilizzato per la raccolta del fior di sale. Il retino sottile che forma la pala consente di trattenere il sottile velo di sale superficiale (fior di sale) formatosi sulla superficie delle vasche salanti separandolo dalla salamoia sottostante. Tutto il processo è rigorosamente manuale.",
    ENdescription: "This tool is used for harvesting the 'Fior di Sale'. The sieving-shovel allows to keep the thin layer of salt cristals (fior di sale) grown on the crystallizer pan surface separating it from the underlying brine. The whole process is strictly executed by hand.",
  },
  page05: {
    title: "Rastreddru",
    sectionNumber: "05",
    image: "./src/assets/Rastreddu.png",
    alt: "",
    ITdescription: "Strumento ideato ed utilizzato per la raccolta del fior di sale. Il retino sottile che forma la pala consente di trattenere il sottile velo di sale superficiale (fior di sale) formatosi sulla superficie delle vasche salanti separandolo dalla salamoia sottostante. Tutto il processo è rigorosamente manuale.",
    ENdescription: "This tool is used for harvesting the 'Fior di Sale'. The sieving-shovel allows to keep the thin layer of salt cristals (fior di sale) grown on the crystallizer pan surface separating it from the underlying brine. The whole process is strictly executed by hand.",
  },
  page06: {
    title: "Pala di rumpiri",
    sectionNumber: "06",
    image: "./src/assets/PaluDiRumpiri.png",
    alt: "",
    ITdescription: "Strumento ideato ed utilizzato per la raccolta del fior di sale. Il retino sottile che forma la pala consente di trattenere il sottile velo di sale superficiale (fior di sale) formatosi sulla superficie delle vasche salanti separandolo dalla salamoia sottostante. Tutto il processo è rigorosamente manuale.",
    ENdescription: "This tool is used for harvesting the 'Fior di Sale'. The sieving-shovel allows to keep the thin layer of salt cristals (fior di sale) grown on the crystallizer pan surface separating it from the underlying brine. The whole process is strictly executed by hand.",
  },
  page07: {
    title: "Pala di carricatu",
    sectionNumber: "07",
    image: "./src/assets/Pala_Di_Carricatu.png",
    alt: "",
    ITdescription: "Strumento ideato ed utilizzato per la raccolta del fior di sale. Il retino sottile che forma la pala consente di trattenere il sottile velo di sale superficiale (fior di sale) formatosi sulla superficie delle vasche salanti separandolo dalla salamoia sottostante. Tutto il processo è rigorosamente manuale.",
    ENdescription: "This tool is used for harvesting the 'Fior di Sale'. The sieving-shovel allows to keep the thin layer of salt cristals (fior di sale) grown on the crystallizer pan surface separating it from the underlying brine. The whole process is strictly executed by hand.",
  },
  page08: {
    title: "Paluneddu",
    sectionNumber: "08",
    image: "./src/assets/Paluneddu.jpg",
    alt: "",
    ITdescription: "Strumento ideato ed utilizzato per la raccolta del fior di sale. Il retino sottile che forma la pala consente di trattenere il sottile velo di sale superficiale (fior di sale) formatosi sulla superficie delle vasche salanti separandolo dalla salamoia sottostante. Tutto il processo è rigorosamente manuale.",
    ENdescription: "This tool is used for harvesting the 'Fior di Sale'. The sieving-shovel allows to keep the thin layer of salt cristals (fior di sale) grown on the crystallizer pan surface separating it from the underlying brine. The whole process is strictly executed by hand.",
  },
  page09: {
    title: "Carriola",
    sectionNumber: "09",
    image: "./src/assets/Carriola.png",
    alt: "",
    ITdescription: "Strumento ideato ed utilizzato per la raccolta del fior di sale. Il retino sottile che forma la pala consente di trattenere il sottile velo di sale superficiale (fior di sale) formatosi sulla superficie delle vasche salanti separandolo dalla salamoia sottostante. Tutto il processo è rigorosamente manuale.",
    ENdescription: "This tool is used for harvesting the 'Fior di Sale'. The sieving-shovel allows to keep the thin layer of salt cristals (fior di sale) grown on the crystallizer pan surface separating it from the underlying brine. The whole process is strictly executed by hand.",
  },
};

